import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './components/SessionProvider'
import '../../node_modules/bootstrap/dist/css/bootstrap.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-100'>
      <body className="h-100" style={{background:"#D8D9DA"}}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
